Rest API
podlove/podlove-publisher pull request #1248
Opened 2021-11-07 11:35 UTC by dnkbln

Hallo Eric,

hier ist mein aktueller Stand beim Erstellen der Rest API.

2022-01-30 19:56 UTC, eteubert requested changes
Wow, was für ein Brocken :D Habe ein paar Anmerkungen im hinterlassen, aber grundlegend passt das. 🚀

2022-01-31 15:21 UTC, dnkbln commented on lib/api/validation.php
> +            if (strlen($param) < 255)
Du hast recht, ich habe es geändert.

2022-02-02 20:40 UTC, dnkbln commented on lib/api/validation.php
> +        if (!isset($param))
Done

2022-02-02 20:40 UTC, dnkbln commented on lib/api/validation.php
> +        if (is_bool($npt) === true && $npt === false)
Done

2022-02-02 20:41 UTC, dnkbln commented on includes/api/chapters.php
> +                        'description' => __('List of chapters, please use mp4chpat format.'),
Done

2022-02-02 20:41 UTC, dnkbln commented on includes/api/episodes.php
> +                    'description' => __('Unique identifier for the episode.'),
Done

2022-02-02 20:41 UTC, dnkbln commented on lib/modules/contributors/rest_api.php
> +                        'description' => __('Avatar of the contrbutor'),
Done

2022-02-05 13:21 UTC, dnkbln commented on includes/api/episodes.php
> +class WP_REST_PodloveEpisodeContributor_Controller extends WP_REST_Controller
Done und Postman Test angepasst

2022-02-05 13:25 UTC, dnkbln commented on lib/modules/transcripts/rest_api.php
> +        if (isset($request['offset']))
Done

2022-02-05 13:25 UTC, dnkbln commented on lib/modules/transcripts/rest_api.php
> +    public function get_item( $request )
Done

2022-02-05 13:26 UTC, dnkbln commented on lib/modules/transcripts/model/transcript.php
> +			ORDER BY t.start ASC';
Done

2022-02-05 13:49 UTC, dnkbln commented on lib/modules/contributors/rest_api.php
> +
Done

2022-02-05 14:31 UTC, dnkbln commented on lib/modules/contributors/rest_api.php
> +            if ($contributor->visibility != 1) {
Damit ich die Prüfung nicht erst in der Funktion get_items bzw get_item mache, habe ich den Endpunkt um den Parameter filter=all|visible ergänzt. Wird kein Filter angegeben, so wird von visible ausgegangen. Ist der filter all aktiv, so wird in get_item_permissions_check geprüft, ob der Benutzer ausreichend Rechte hat.
Dies gilt für podlove/v2/contributor und podlove/v2/contributor/{id}.

2022-02-05 14:39 UTC, dnkbln commented
Hallo Eric, ich habe deine Anmerkungen eingebaut. Beim letzten Punkt brauche ich deine Hilfe. Ich weiß nicht, was ich dort ändern soll.

2022-02-05 20:32 UTC, eteubert commented
@dnkbln wo ist die Klasse `WP_REST_PodloveEpisodeContributions_Controller` hin, hast du vielleicht nur vergessen die neue Datei einzuchecken? :) Sonst sieht's gut aus 👍 Den change zum letzten Kommentar kann ich gerne selbst nach dem merge umbauen.

2022-02-05 21:19 UTC, dnkbln commented
Sorry. Ich habe das File hinzugefügt.

2022-02-08 18:58 UTC, merged

2022-02-11 11:41 UTC, eteubert commented on lib/modules/transcripts/model/transcript.php
> +        return $wpdb->get_results($sql);
@dnkbln das meinte ich: https://github.com/podlove/podlove-publisher/commit/ef47c210862ab0613ea178be98a58f43e79db42f